version: '3.8'

services:

  # PHP FPM Service
  php:
    container_name: php
    build:
      context: ./docker
    volumes:
      - .:/prototype
    depends_on:
      - maria_db

  # Nginx Service
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - .:/prototype
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    depends_on:
      - php
  maria_db:
    container_name: maria_db
    image: mariadb:latest
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prototype_db
      MYSQL_USER: prototype
      MYSQL_PASSWORD: pRH3fnn3
volumes:
  db-data:
